//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roottech.Tracking.RTM.Boundries.UI.Web.Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Language
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Language()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roottech.Tracking.RTM.Boundries.UI.Web.Resources.Language", typeof(Language).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string.
		/// </summary>
		/// 
		private static string ReturnPhraseNotFoundWhenNullOrEmpty(string Phrase)
		{
			return (string.IsNullOrEmpty(Phrase) ? ResourceManager.GetString("PhraseNotFound", resourceCulture) : Phrase);
		}
		public static string GetSeverityValue(string severity)
		{
			switch (severity.ToLower())
			{
				case "high":
					return High;
				case "medium":
					return Medium;
				case "low":
					return Low;
				default:
					return "";
			}
		}

        public static string GetDescription(string description) {
            return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString(description, resourceCulture));

        }
		public static string High
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("High", resourceCulture));

			}
		}

        public static string at {
            get {
                return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("at", resourceCulture));

            }
        }

        public static string With {
            get {
                return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("With", resourceCulture));

            }
        }
		public static string ErrorEmailTitle
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("ErrorEmailTitle", resourceCulture));
			}
		}

		public static string Medium
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Medium", resourceCulture));
			}
		}

		public static string Low
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Low", resourceCulture));
			}
		}

		public static string Severity
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Severity", resourceCulture));
			}
		}

		public static string Code
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Code", resourceCulture));
			}
		}

		public static string Description
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Description", resourceCulture));
			}
		}

		public static string Timestamp
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Timestamp", resourceCulture));
			}
		}

		public static string New
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("New", resourceCulture));
			}
		}

		public static string Errors
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Errors", resourceCulture));
			}
		}

		public static string Prior
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Prior", resourceCulture));
			}
		}

		public static string Has
		{
			get
			{
				return ReturnPhraseNotFoundWhenNullOrEmpty(ResourceManager.GetString("Has", resourceCulture));
			}
		}

	}
}
